### ISSUE TITLE
Feature request: usability of the Either monad

### ISSUE THREAD

**Issue by nrnrnr** [kuribas/mfsolve#4]
If `addEquation` and `getKnown` used the same error type, they could be used together in the `Either` monad, which would be convenient.  As it is stands, I resort to something like the following.

```
    where c0 :: Either (DepError SimpleVar Double) Double
          c0 = do d1 <- addEquality noDeps (eqn p1) "c0"
                  d2 <- addEquality d1 (eqn p2)     "c0"
                  soln <- addEquality d2 (eqn p3)   "c0"
                  first (const $ UndefinedVar "c0") $ getKnown "c0" soln
```

**Comment by kuribas** [comment]
Well they were meant for low level operations.  The monadic interface has unified error messages.  For example you could use `(===)` and `getValue`.  Would that work?

**Comment by kuribas** [comment]
I am closing this, since with the new monadic API, you can do:

```
 where
   v0 = makeVariable (SimpleVar "c0")
   c0 :: Either (DepError SimpleVar Double) Double
   c0 = flip evalSolver noDeps $ do
     eq1 === v0
     eq2 === v0
     eq3 === v0
     getValue (SimpleVar "c0")
```
