### ISSUE TITLE
Build failures with mtl-2.3

### ISSUE THREAD

**Issue by sjakobi** [kuribas/mfsolve#9]
```
Math/MFSolve.hs:269:41: error:
    Not in scope: type constructor or class ‘ExceptT’
    |
269 |   MFSolverT (StateT (Dependencies v n) (ExceptT (DepError v n) m) a)
    |                                         ^^^^^^^
```

All versions on Hackage seem affected.

As a Hackage trustee I have created revisions for these versions that should prevent users from encountering these errors. See e.g. https://hackage.haskell.org/package/mfsolve-0.3.2.1/revisions/.

**Comment by sjakobi** [comment]
Note that a bug-fix version of  `mtl` should bring back the re-export of `ExceptT`: https://github.com/haskell/mtl/issues/117

However, earlier testing with a release canditate for `mtl-2.3` revealed more compatibility issues.

**Comment by ysangkok** [comment]
This was fixed in https://hackage.haskell.org/package/mfsolve-0.3.2.2 and the issue can be closed.
